name: Java CI with Maven

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean install

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login into Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_USER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USER_NAME }}/spring_boot_ci_cd:${{ github.sha }}

    - name: Deploy into EC2 Instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_HOST_USERNAME }}
        key: ${{ secrets.EC2_HOST_KEY }}
        script: |
          # Ensure Docker is installed
          if ! command -v docker &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y docker.io
          fi

          # Allow user to run docker
          sudo usermod -aG docker $USER
          sudo chmod 777 /var/run/docker.sock

          # Stop and remove old container if it exists
          docker stop Spring_Boot_CI_CD || true
          docker rm Spring_Boot_CI_CD || true

          # Pull new image and run it
          docker pull ${{ secrets.DOCKER_USER_NAME }}/spring_boot_ci_cd:${{ github.sha }}
          docker run -d --name Spring_Boot_CI_CD -p 8080:9090 ${{ secrets.DOCKER_USER_NAME }}/spring_boot_ci_cd:${{ github.sha }}
